--liquibase formatted sql

--changeset TimurKhamzin:1
--comment first migration

CREATE TABLE IF NOT EXISTS t_orders
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_number VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS t_order_line_items
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sku_code VARCHAR(255)   NOT NULL,
    price    NUMERIC(38, 2) NOT NULL,
    quantity INTEGER        NOT NULL,
    order_id BIGINT REFERENCES t_orders (id) ON DELETE CASCADE
);